### ISSUE TITLE
Video.js updates

### ISSUE THREAD

**Issue by gkatsev** [kensgists/apt#6]
- multiple audio tracks are now supported natively as of v5.10.1.
- youtube plugin is now at videojs/videojs-youtube
- I would recommend brightcove/playlists as a much more maintained and feature full playlists library
- audio only support by using the `<audio>` tag in the embed code
- annotations by author is available via the brightove/videojs-overlay
- media-sources support should be linking to https://www.npmjs.com/package/videojs-contrib-media-source
- we do not have EME support yet but it's coming.

**Comment by OwenEdwards** [comment]
Thanks @gkatsev, I'll get those things updated.

Note to self:
https://www.npmjs.com/package/videojs-youtube
https://www.npmjs.com/package/videojs-playlist and https://www.npmjs.com/package/videojs-playlist-ui
https://www.npmjs.com/package/videojs-overlay
https://www.npmjs.com/package/videojs-contrib-media-sources
